version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: quiz_app
    volumes:
      - ./quiz_app.sql:/docker-entrypoint-initdb.d/quiz_app.sql
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_NAME: quiz_app
